name: Test

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.17.0"
          cache: npm
      - name: Test
        run: npm ci && npm run check && npm t
